package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.event.ActionEvent;

public class AddUserController {
	@FXML
	private Button OK;
	@FXML
	private Button OTMENA;

	// Event Listener on Button[#OK].onAction
	@FXML
	public void onOk(ActionEvent event) {
		// TODO Autogenerated
		try {
			BorderPane root = (BorderPane)FXMLLoader.load(getClass().getResource("dobavlenie.fxml"));
			Scene scene = new Scene(root,500,250);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			Main.stage.setScene(scene);
			Main.stage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#OTMENA].onAction
	@FXML
	public void OnOTMENA(ActionEvent event) {
		// TODO Autogenerated
		try {
			BorderPane root = (BorderPane)FXMLLoader.load(getClass().getResource("reg.fxml"));
			Scene scene = new Scene(root,250,300);
			scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
			Main.stage.setScene(scene);
			Main.stage.show();
		} catch(Exception e) {
			e.printStackTrace();
		}
	}
}
