package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class dobavlenieController {
	@FXML
	private Button ok;

	// Event Listener on Button[#ok].onAction
	@FXML
	public void okei(ActionEvent event) {
		// TODO Autogenerated
	}
}
