package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.layout.BorderPane;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

public class glTableController implements Initializable {
	@FXML
	private Button BEK;
	@FXML
	private Button OBNOVA;
	@FXML
	private Button DEL;
	@FXML
	private Button IZM;
	@FXML
	private Button dob;
	 @FXML
	    private ListView<String> onMainUser;
	
	ObservableList <String> users = FXCollections.observableArrayList();

	// Event Listener on Button[#BEK].onAction
	@FXML
	public void onBEK(ActionEvent event) {
		// TODO Autogenerated
		 try {
			 
				BorderPane root = (BorderPane)FXMLLoader.load(getClass().getResource("reg.fxml"));
				Scene scene = new Scene(root,250,300);
				scene.getStylesheets().add(getClass().getResource("application.css").toExternalForm());
				Main.stage.setScene(scene);
				Main.stage.show();
			} catch(Exception e) {
				e.printStackTrace();
			}
	}
	// Event Listener on Button[#OBNOVA].onAction
	@FXML
	public void onOBNOVA(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#DEL].onAction
	@FXML
	public void onDEL(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#IZM].onAction
	@FXML
	public void onIZM(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#dob].onAction
	@FXML
	public void onDOB(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		users.add("user1");
		users.add("user2");
		users.add("user3");
		onMainUser.setItems(users);
	}
	@FXML
    void onMainUser(ActionEvent event) {

    }
}
