package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.scene.control.TableColumn;

public class SampleController implements Initializable{
	@FXML
	private TableView table;
	 @FXML
	    private TableColumn<User,String> colPassword;

	    @FXML
	    private TableColumn<User,String> colUser;
	@FXML
	private Button obnovit;
	@FXML
	private Button ydolit;
	@FXML
	private Button izmenit;
	@FXML
	private Button dobavit;

	ObservableList<User>users=FXCollections.observableArrayList();
	// Event Listener on Button[#obnovit].onAction
	@FXML
	public void onr(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#ydolit].onAction
	@FXML
	public void ondel(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#izmenit].onAction
	@FXML
	public void onref(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#dobavit].onAction
	@FXML
	public void onadd(ActionEvent event) {
		// TODO Autogenerated
		
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
		colUser.setCellValueFactory(new PropertyValueFactory<User,String>("login"));
		colPassword.setCellValueFactory(new PropertyValueFactory<User,String>("password"));
		table.setItems(users);
	}
}
